"""delete and recreate database

Revision ID: 118e3ca6562b
Revises: 
Create Date: 2023-02-11 15:28:17.192350

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '118e3ca6562b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('item',
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('spirit', sa.String(), nullable=True),
    sa.Column('flavor', sa.String(), nullable=True),
    sa.Column('bottle', sa.String(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('item_id')
    )
    op.create_table('label',
    sa.Column('label_id', sa.Integer(), nullable=False),
    sa.Column('name_font', sa.String(), nullable=True),
    sa.Column('message_font', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('message', sa.String(), nullable=True),
    sa.Column('image', sa.String(), nullable=True),
    sa.Column('item_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['item.item_id'], ),
    sa.PrimaryKeyConstraint('label_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('label')
    op.drop_table('item')
    # ### end Alembic commands ###
