"""add email to item3

Revision ID: 39f3fc157ea9
Revises: 8783792a16c9
Create Date: 2023-02-11 13:41:25.260290

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '39f3fc157ea9'
down_revision = '8783792a16c9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item', sa.Column('email', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('item', 'email')
    # ### end Alembic commands ###
