"""added corrected datatypes back in

Revision ID: 403abbf5418a
Revises: e5d67cc1d77d
Create Date: 2023-01-26 18:34:01.905569

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '403abbf5418a'
down_revision = 'e5d67cc1d77d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customer', sa.Column('phone_number', sa.String(), nullable=True))
    op.add_column('label', sa.Column('font', sa.String(), nullable=True))
    op.add_column('label', sa.Column('message', sa.String(), nullable=True))
    op.add_column('label', sa.Column('name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('label', 'name')
    op.drop_column('label', 'message')
    op.drop_column('label', 'font')
    op.drop_column('customer', 'phone_number')
    # ### end Alembic commands ###
