"""change phone number to String and add is_admin to Customer 3

Revision ID: 4502056856ed
Revises: 3230af799475
Create Date: 2023-01-26 15:18:46.959577

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4502056856ed'
down_revision = '3230af799475'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customer', sa.Column('is_admin', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('customer', 'is_admin')
    # ### end Alembic commands ###
