"""empty message

Revision ID: 6129d699f67b
Revises: 118e3ca6562b
Create Date: 2023-02-12 13:50:38.981378

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6129d699f67b'
down_revision = '118e3ca6562b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('label', sa.Column('background_color', sa.String(), nullable=True))
    op.add_column('label', sa.Column('message_font_color', sa.String(), nullable=True))
    op.add_column('label', sa.Column('name_font_color', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('label', 'name_font_color')
    op.drop_column('label', 'message_font_color')
    op.drop_column('label', 'background_color')
    # ### end Alembic commands ###
