"""separated model relationships

Revision ID: 73c7fe054a77
Revises: 76af8d80908b
Create Date: 2023-02-02 21:27:46.902529

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '73c7fe054a77'
down_revision = '76af8d80908b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('item_order_id_fkey', 'item', type_='foreignkey')
    op.drop_column('item', 'order_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item', sa.Column('order_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('item_order_id_fkey', 'item', 'order', ['order_id'], ['order_id'])
    # ### end Alembic commands ###
