"""add email to item2

Revision ID: 8783792a16c9
Revises: e8e535adf8bf
Create Date: 2023-02-11 13:41:07.541909

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8783792a16c9'
down_revision = 'e8e535adf8bf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('item', 'email')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item', sa.Column('email', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
