"""empty message

Revision ID: b34250f75b65
Revises: d5fbb0e1cd05
Create Date: 2023-02-09 14:20:42.204338

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b34250f75b65'
down_revision = 'd5fbb0e1cd05'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('label', sa.Column('image', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('label', 'image')
    # ### end Alembic commands ###
