"""deleted insorrect datatypes- will change and add back

Revision ID: e5d67cc1d77d
Revises: f4042f90f231
Create Date: 2023-01-26 18:32:18.469536

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e5d67cc1d77d'
down_revision = 'f4042f90f231'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('customer', 'phone_number')
    op.drop_column('label', 'message')
    op.drop_column('label', 'font')
    op.drop_column('label', 'name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('label', sa.Column('name', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('label', sa.Column('font', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('label', sa.Column('message', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('customer', sa.Column('phone_number', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
