"""add email to item

Revision ID: e8e535adf8bf
Revises: b34250f75b65
Create Date: 2023-02-11 13:39:19.131320

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e8e535adf8bf'
down_revision = 'b34250f75b65'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item', sa.Column('email', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('item', 'email')
    # ### end Alembic commands ###
