"""empty message

Revision ID: f68bdfd59bcd
Revises: 6129d699f67b
Create Date: 2023-02-13 23:15:48.025818

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f68bdfd59bcd'
down_revision = '6129d699f67b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item', sa.Column('status', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('item', 'status')
    # ### end Alembic commands ###
